@startmindmap

<style>
node {
    MaximumWidth 250
}
</style>

* <size:24><b>OAuth 2.0</b></size>
** <b>Grants</b>
*** Authorization code grant type
****:Proof Key for Code Exchange (PKCE)
Allows authorization server to verify authorization and token request came from the same client;
**** Replaced implicit flow by allowing public clients to use auth code flow
***** No longer need to send access token in front channel (URL fragment)
***** Better supports short token lifetime, as can use short access token + refresh token
***[#red] Implicit grant type
****:Get tokens directly from authorization request
Originally for browser based public clients that couldn't protect client secrets
Generally deprecated in favour of auth code + PKCE;
***[#red] Resource owner grant type
****:Client trades username + password for tokens
Generally deprecated because clients should not see
resource owner credentials;
*** Client credentials grant type
**** No resource owner\nExchange client ID + secret for tokens
*** Assertion grant type
**** Client is given a signed assertion it passes to resource server in exchange for tokens

**[#LightSkyBlue] <b>OpenID Connect 1.0 (OIDC)</b>
*** An identity layer built on top of OAuth 2.0 enabling verification end-user identity based on authentication performed by an Authorization Server

left side

** <b>What is OAuth 2.0</b>
*** A delegated authorization protocol
*** Allows a resource owner to grant access to a resource they control to another piece of software

** <b>Roles</b>
*** Resource Owner
**** Entity able to grant access to a resource, usually a person controlling the client software
****[#LightSkyBlue] OIDC
*****[#LightSkyBlue] End-User
*** Client
**** The software that sends user for auth, and accesses the protected resource on behalf of the resource owner using tokens (client doesn't necessarily a web browser, can be e.g. a server)
**** Client types
***** Confidential client
****** Clients capable of keeping secret credentials, e.g. server side clients
***** Public client
****** Clients not capable of keeping secret credentials, e.g. SPAs or native apps
****[#LightSkyBlue] OIDC
*****[#LightSkyBlue] Relying Party (RP)
*** Authorization Server
**** Server able to authenticate and authorize resource owners and issue tokens
****[#LightSkyBlue] OIDC
*****[#LightSkyBlue] OpenID Provider (OP)
******[#LightSkyBlue] An authorization server capable of authentication a user and providing an OIDC ID token
*** Resource Server
**** Sever hosting protected resources. Can accept requests for protected resources with access tokens

** <b>Tokens</b>
*** Access token
**** Credentials used to access protected resources
*** Refresh token
**** Credentials used to obtain new access tokens when current ones have expired.
***[#LightSkyBlue] ID token
**** Part of OIDC. A security token that contains claims about the authentication of a user, such as their ID (sub)
@endmindmap
