name: OAuth

on: push

jobs:
  client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - run: npm ci
        working-directory: ./client
      - run: npm run types
        working-directory: ./client

  authorisation-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - run: npm ci
        working-directory: ./authorisation-server
      - run: npm run types
        working-directory: ./authorisation-server
      - run: npm test
        working-directory: ./authorisation-server

  resource-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - run: npm ci
        working-directory: ./resource-server
      - run: npm run types
        working-directory: ./resource-server
      - run: npm test
        working-directory: ./resource-server
